name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - uses: actions/checkout@v4

      # Instala o compilador gcc
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y gcc

      # Compila o projeto
      - name: Build the project
        run: gcc -o brasfoot BrasfootIME.c main.c -I.

      # (Opcional) Executa o programa
      - name: Run the program
        run: ./brasfoot
        continue-on-error: true  # Continua mesmo se o programa falhar (por exemplo, se ele esperar entrada do usuário)
